### ISSUE TITLE
a pv_load should be sufficient to enter dependency structure

### ISSUE THREAD

**Issue by kostrzewa** [martin-ueding/paramvalf#17]
AFAICT, when a file does not perform a ```pv_save```, it will not be executed by ```paramvalf-run```. This is problematic when using paramvalf for plotting, as there is generally no output other than plots in this case.

**Comment by martin-ueding** [comment]
One could even argue that any file in the `paramval` directory should be included in the dependency hierarchy.

Make must have a target for each rule. If we would specify some dummy which is not actually created on disk, we have the problem that the given script would be executed every single time. So we do need some target that is actually created. I see two options:

1. The user must specify a special comment like `# Creates: my-plot.pdf`. Then Make can check whether the script needs running.

2. We create an automatic dummy target like `foo.R.dummy` for `foo.R` and change the rule in the `Makefile` such that we have a `touch $@` in there to create the file. This way the script is also not run and the user does not have to do anything.

I guess the second option is better because it does the right thing in any case and does not burden the user with anything. I'll implement that.

**Comment by martin-ueding** [comment]
I think that the correct entry is now added to the `Makefile`.
