### ISSUE TITLE
write_unchanged does not really work

### ISSUE THREAD

**Issue by kostrzewa** [martin-ueding/paramvalf#24]
This is not a very insightful issue report, but it seems to me that using `write_unchanged = FALSE` in practice leads to issues with dependencies. Perhaps this is my own fault as I have a long file which reads a bunch of `tsv` files to set up some global parameters for the analysis. When I change a single one of these `tsv` files, of course the file is rerun and all the resulting `pv_save` are called, causing dependency resolution to rerun the entire analysis.

I had hoped that I could avert this by using `write_unchanged = FALSE` in this case, but it seems that this causes the file to be rerun many times (10 or so in a row) and some, but not all, of the dependency tree to be regenerated.

I wonder if there's anything I can do beyond splitting this script up into many files which process only one or two tsv files each. I might then add a convenience wrapper which sources all of these individual scripts in case I want to run the analysis setup manually.

**Comment by martin-ueding** [comment]
I'd say that you should split the scripts such that they only produce a single Rdata file. Then the dependency resolution can work better.

This special option was just built in because we basically back-propagated things. For the fits in the rho we needed to specify the fit ranges and also which GEVP reference time we wanted. But the GEVP reference times did not depend on the fit ranges. We did use a single file for this and therefore changing a fit range would re-run the GEVP. The clean solution in terms of the framework would have been to split it into two files. But then one would have to already know which GEVP reference times are used in the fits later on. We therefore have this really strange thing, but I think that one should change it differently somehow.

**Comment by kostrzewa** [comment]
Alright, sounds good, thanks!
